name: CI/CD Telegram-Bot → AWS Lambda

on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:   ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:          eu-central-1

      - name: Deploy via AWS SAM
        run: |
          sam deploy \
            --template-file template.yaml \
            --stack-name telegram-bot \
            --capabilities CAPABILITY_IAM \
            --region eu-central-1 \
            --no-confirm-changeset \
            --parameter-overrides \
              ParameterKey=BotToken,ParameterValue=${{ secrets.BOT_TOKEN }} \
              ParameterKey=ChatIds,ParameterValue=${{ secrets.CHAT_ID }}